# Generated by Django 4.1.3 on 2023-09-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0010_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilecat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('services', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Uploads\\profile')),
                ('status', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ink_Spot.profilecat')),
            ],
        ),
    ]
