# Generated by Django 4.2.5 on 2023-09-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0011_profilecat_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='language',
            new_name='brand',
        ),
    ]
