# Generated by Django 4.2.5 on 2023-09-29 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0012_rename_language_book_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
