# Generated by Django 4.2.5 on 2023-09-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0013_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
    ]
