# Generated by Django 4.2.5 on 2023-09-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0014_remove_book_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='a_uth',
            new_name='owner',
        ),
    ]
