# Generated by Django 4.2.5 on 2023-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0018_rename_desc_book_about_rename_name_book_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
