# Generated by Django 4.2.5 on 2023-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0019_alter_book_contact_alter_book_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='empty', max_length=400)),
            ],
        ),
    ]
