# Generated by Django 4.2.5 on 2023-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0020_pform'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(default='Hyderabad', max_length=300),
        ),
    ]
