# Generated by Django 4.2.5 on 2023-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0024_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offcial_phone', models.CharField(default=7330012300, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
