# Generated by Django 4.2.5 on 2023-10-08 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0025_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(blank=True, default='none', max_length=100)),
                ('company', models.CharField(blank=True, default='none', max_length=100)),
                ('modal', models.CharField(blank=True, default='none', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ink_Spot.customer')),
            ],
        ),
    ]
