# Generated by Django 4.2.5 on 2023-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0026_rhis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_1',
            field=models.ImageField(upload_to='Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_2',
            field=models.ImageField(upload_to='Uploads/Books'),
        ),
    ]
