# Generated by Django 4.2.5 on 2023-10-09 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0027_alter_book_image_alter_book_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
