# Generated by Django 4.2.5 on 2023-10-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0029_order_deliverd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='dispatch',
        ),
    ]
