# Generated by Django 4.2.5 on 2023-10-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0031_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(default=models.CharField(max_length=15), max_length=500),
        ),
    ]
