# Generated by Django 4.2.5 on 2023-10-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0032_customer_address_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='Uploads/Books/1.jpg', upload_to='Uploads/Books'),
        ),
        migrations.AddField(
            model_name='contact',
            name='image_1',
            field=models.ImageField(default='Uploads/Books/1.jpg', upload_to='Uploads/Books'),
        ),
        migrations.AddField(
            model_name='contact',
            name='image_2',
            field=models.ImageField(default='Uploads/Books/1.jpg', upload_to='Uploads/Books'),
        ),
    ]
