# Generated by Django 4.2.5 on 2023-11-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0033_contact_image_contact_image_1_contact_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='USER@GMAIL.COM', max_length=254),
        ),
    ]
