# Generated by Django 4.2.5 on 2023-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0034_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='abcd@gmail.com', max_length=300),
        ),
    ]
