# Generated by Django 4.2.5 on 2024-01-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0037_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='statics/Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_1',
            field=models.ImageField(upload_to='statics/Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_2',
            field=models.ImageField(upload_to='statics/Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='statics/Uploads/Books/1.jpg', upload_to='statics/Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image_1',
            field=models.ImageField(default='statics/Uploads/Books/1.jpg', upload_to='statics/Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image_2',
            field=models.ImageField(default='statics/Uploads/Books/1.jpg', upload_to='statics/Uploads/Books'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='statics/Uploads/profile'),
        ),
    ]
